# Configuration file for unit test runner.
language: php
env:
  global:
    - XDEBUG_MODE=coverage
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
before_script:
  - composer install
  - mkdir -p build/logs
script: composer test-coverage
notifications:
  email: true
sudo: false
after_success:
    - travis_retry php vendor/bin/php-coveralls
